// <auto-generated />
using System;
using FlugsportWienOgn.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlugsportWienOgn.Database.Migrations
{
    [DbContext(typeof(FlightDbContext))]
    [Migration("20250618070949_AddCourseToFlightPathItem")]
    partial class AddCourseToFlightPathItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftType")
                        .HasColumnType("integer");

                    b.Property<int>("Altitude")
                        .HasColumnType("integer");

                    b.Property<string>("CallSign")
                        .HasColumnType("text");

                    b.Property<string>("FlarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<float>("VerticalSpeed")
                        .HasColumnType("real");

                    b.Property<float>("VerticalSpeedAverage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FlarmId")
                        .IsUnique();

                    b.ToTable("Aircraft");
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.CleanupStamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("LastCleanup")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Cleanup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastCleanup = new DateOnly(2025, 6, 17)
                        });
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.FlightPathItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<int>("Altitude")
                        .HasColumnType("integer");

                    b.Property<int>("Course")
                        .HasColumnType("integer");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<int>("Speed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("VerticalSpeed")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("FlightData");
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.FlightbookEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer");

                    b.Property<string>("AirfieldIcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LandingTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LaunchHeight")
                        .HasColumnType("integer");

                    b.Property<int>("LaunchType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TakeOffTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("FlightbookEntry");
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.KnownAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftType")
                        .HasColumnType("integer");

                    b.Property<string>("FlarmId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<int>("OwnershipType")
                        .HasColumnType("integer");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationShort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlarmId")
                        .IsUnique();

                    b.ToTable("KnownAircraft");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AircraftType = 1,
                            FlarmId = "DD98B4",
                            Model = "Ventus 2b",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-0544",
                            RegistrationShort = "DR"
                        },
                        new
                        {
                            Id = 2,
                            AircraftType = 1,
                            FlarmId = "DD9EA3",
                            Model = "LS4",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-2526",
                            RegistrationShort = "DL"
                        },
                        new
                        {
                            Id = 3,
                            AircraftType = 1,
                            FlarmId = "DDAD0C",
                            Model = "ASK 21",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-3931",
                            RegistrationShort = "DZ"
                        },
                        new
                        {
                            Id = 4,
                            AircraftType = 1,
                            FlarmId = "DD98C1",
                            Model = "LS4",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-9104",
                            RegistrationShort = "DV"
                        },
                        new
                        {
                            Id = 5,
                            AircraftType = 1,
                            FlarmId = "3F0625",
                            Model = "Discus‑2b",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-9614",
                            RegistrationShort = "D2B"
                        },
                        new
                        {
                            Id = 6,
                            AircraftType = 1,
                            FlarmId = "DD9537",
                            Model = "ASK 21",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-5446",
                            RegistrationShort = "DX"
                        },
                        new
                        {
                            Id = 7,
                            AircraftType = 1,
                            FlarmId = "DDAF0B",
                            Model = "DG 300 Elan",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-5491",
                            RegistrationShort = "91"
                        },
                        new
                        {
                            Id = 8,
                            AircraftType = 1,
                            FlarmId = "4404FD",
                            Model = "Ventus 2b",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-5603",
                            RegistrationShort = "DS"
                        },
                        new
                        {
                            Id = 9,
                            AircraftType = 1,
                            FlarmId = "DD9F86",
                            Model = "DG 500 Orion",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-5711",
                            RegistrationShort = "DI"
                        },
                        new
                        {
                            Id = 20,
                            AircraftType = 3,
                            FlarmId = "DD9382",
                            Model = "Dimona HK 36 TTC",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "D-KRES",
                            RegistrationShort = "RES"
                        },
                        new
                        {
                            Id = 21,
                            AircraftType = 3,
                            FlarmId = "440524",
                            Model = "Dimona HK 36 TTC",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-9466",
                            RegistrationShort = "466"
                        },
                        new
                        {
                            Id = 22,
                            AircraftType = 3,
                            FlarmId = "440523",
                            Model = "Katana DA 20 A1",
                            Owner = "ASKÖ Flugsport Wien",
                            OwnershipType = 0,
                            Registration = "OE-CBB",
                            RegistrationShort = "CBB"
                        },
                        new
                        {
                            Id = 101,
                            AircraftType = 1,
                            FlarmId = "D0114B",
                            Model = "DG‑600",
                            Owner = "Andreas Stocker",
                            OwnershipType = 1,
                            Registration = "D-6000",
                            RegistrationShort = "MI"
                        },
                        new
                        {
                            Id = 102,
                            AircraftType = 1,
                            FlarmId = "D0287B",
                            Model = "LS1‑f",
                            Owner = "Julia Götz",
                            OwnershipType = 1,
                            Registration = "D-2254",
                            RegistrationShort = "HR"
                        },
                        new
                        {
                            Id = 103,
                            AircraftType = 1,
                            FlarmId = "D02864",
                            Model = "HPH 304S Shark",
                            Owner = "Andreas Stocker / Julia Götz",
                            OwnershipType = 1,
                            Registration = "D-KHJH",
                            RegistrationShort = "JA"
                        },
                        new
                        {
                            Id = 105,
                            AircraftType = 1,
                            FlarmId = "D0019F",
                            Model = "DG‑800",
                            Owner = "Stephan Haupt",
                            OwnershipType = 1,
                            Registration = "D-KEVA",
                            RegistrationShort = "O2"
                        },
                        new
                        {
                            Id = 106,
                            AircraftType = 1,
                            FlarmId = "F64550",
                            Model = "Ka‑8",
                            Owner = "Christoph Urach",
                            OwnershipType = 1,
                            Registration = "D-1890",
                            RegistrationShort = "KA8"
                        },
                        new
                        {
                            Id = 107,
                            AircraftType = 1,
                            FlarmId = "DF23C3",
                            Model = "Arcus M",
                            Owner = "Markus Podivin / Irmgard Paul / Josef Pannagl",
                            OwnershipType = 1,
                            Registration = "D-KWMR",
                            RegistrationShort = "MR"
                        },
                        new
                        {
                            Id = 108,
                            AircraftType = 1,
                            FlarmId = "3EEC8B",
                            Model = "HPH 304CZ‑17",
                            Owner = "Sören Rossow",
                            OwnershipType = 1,
                            Registration = "D-3060",
                            RegistrationShort = "CZ"
                        },
                        new
                        {
                            Id = 109,
                            AircraftType = 1,
                            FlarmId = "3EFBA7",
                            Model = "ASW 28",
                            Owner = "Mario Neumann / Kathrin Havemann",
                            OwnershipType = 1,
                            Registration = "D-6928",
                            RegistrationShort = "SI"
                        },
                        new
                        {
                            Id = 110,
                            AircraftType = 1,
                            FlarmId = "DDB2C4",
                            Model = "SF-27",
                            Owner = "Fabian Hoffmann",
                            OwnershipType = 1,
                            Registration = "OE-0789",
                            RegistrationShort = "FH"
                        },
                        new
                        {
                            Id = 111,
                            AircraftType = 1,
                            FlarmId = "D006D6",
                            Model = "EB 29 DR",
                            Owner = "Christoph Jütte",
                            OwnershipType = 1,
                            Registration = "D-KXAC",
                            RegistrationShort = "AC"
                        },
                        new
                        {
                            Id = 113,
                            AircraftType = 1,
                            FlarmId = "DD91B7",
                            Model = "DG-200",
                            Owner = "Florian Wögerer",
                            OwnershipType = 1,
                            Registration = "D-7868",
                            RegistrationShort = "FLO"
                        },
                        new
                        {
                            Id = 114,
                            AircraftType = 1,
                            FlarmId = "3EFBF6",
                            Model = "Mini Nimbus",
                            Owner = "Ernst Schicker",
                            OwnershipType = 1,
                            Registration = "D-7007",
                            RegistrationShort = "SE"
                        });
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.FlightPathItem", b =>
                {
                    b.HasOne("FlugsportWienOgn.Database.Entities.Aircraft", "Aircraft")
                        .WithMany("FlightPath")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.FlightbookEntry", b =>
                {
                    b.HasOne("FlugsportWienOgn.Database.Entities.Aircraft", "Aircraft")
                        .WithMany("FlightBookEntries")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("FlugsportWienOgn.Database.Entities.Aircraft", b =>
                {
                    b.Navigation("FlightBookEntries");

                    b.Navigation("FlightPath");
                });
#pragma warning restore 612, 618
        }
    }
}
