services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=^matthias.buschbeck@outlook.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_cert:/letsencrypt"

  web:
    image: flugsport-wien-ogn-image
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api-test.flugsportwienogn.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://0.0.0.0:80"

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin$123
      POSTGRES_DB: FlugsportWienOgn
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  traefik_cert: